---
title: "Further Computations with MLEs"
subtitle: "Statistical Estimation for Data Science and AI"
---

[Efficency of Exp MLE]{.column-margin}

::: {#exr-01-exponential-efficiency }
## Efficiency of Exponential MLE Distribution 

Let $X_{1}, X_{2}, \ldots, X_{n}$ 
be a random sample from the exponential distribution with rate $\lambda>0$.

Let $\widehat{\lambda}$, be the MLE for $\widehat{\lambda}$.

Compute the efficiency of $\widehat{\lambda}$

- [ ] $\frac{n}{(n-1)^{2}}$

- [ ] $\frac{n \lambda^{2}}{(n-1)^{2}(n-2)}$

- [ ] $\frac{(n-1)^{2}(n-2)}{n^{3}}$

- [ ] $\frac{\lambda^{2}}{(n-1)^{2}(n-2)}$
:::


::: {.callout-tip}
## Solution

<!-- TODO: link to the definition of efficiency of an estimator in the notes. -->

Recall that the efficiency of  an estimator $\widehat{\theta}$ is defined as the ratio of the Cramer-Rao lower bound (CRLB) to the variance of the estimator:

i.e.

$$
\text{Efficiency}(\widehat{\theta}) = \frac{\mathrm{CRLB}_{\theta,n}}{\mathrm{Var}(\widehat{\theta})}
$$

recall the CRLB is :

$$
\mathrm{CRLB}_{\theta,n} = \frac{1}{I_n(\theta)} = \mathbb{E}\left[\left(\frac{\partial}{\partial \theta} \ln f(\vec{X};\theta)\right)^2\right]^{-1}
$$ 

:::


[asymptotic distribution]{.column-margin}

::: {#exr-02-asymptotic-distribution }
## Asymptotic Distribution of MLE for Tail Probability

Let $X_{1}, X_{2}, \ldots, X_{n}$ 
be a random sample from the exponential distribution with rate $\lambda>0$.

Find the asymptotic distribution of the maximum likelihood estimator for the "tail probability"
$P(X>1)$ for some fixed $x>0$.

(Note: You do not actually need to find the MLE itself!)


- [ ] $N \left( e^{-\lambda} , \lambda^{2} e^{-2 \lambda}/n \right)$

- [ ] $N(\lambda,e^{-2\lambda}/n)$

- [ ] $N(e^{-\lambda},1/(n \lambda^{2}))$

- [ ] $N(\lambda,\lambda^{2}/n)$
:::


::: {.callout-tip}
## Solution

:::

::: {#exr-03-exponential-efficiency }
Let $\widehat{\gamma}_{n}$
be the MLE for the parameter of the Pareto distribution with pdf
$$
f(x;\gamma) =
\begin{cases} 
    \frac{\gamma}{(1+x)^{\gamma+1}} & x > 0\\
    0                               & \text{otherwise} 
\end{cases}
$$
Which of the following are true about $\widehat{\gamma}_{n}$?

(Check all that apply.)

- [ ] $\displaystyle\lim_{n \rightarrow \infty} E[\widehat{\gamma_{n}}]= \gamma$
- [ ] $\widehat{\gamma}_{n}$ has an asymptotic normal distribution.
- [ ] $\widehat{\gamma}_{n}$ is an unbiased estimator of $\gamma$
- [ ] $\widehat{\gamma}_{n}$ does not depend on n
n
:::


::: {.callout-tip}
## Solution
:::

::: {#exr-04-asymptotic-distribution }
## Asymptotic Distribution of Sum of Random Variables

Let $X_{1}, X_{2}, \ldots, X_{n}$ 
be a random sample from from any distribution with mean $\mu$ and variance $\sigma^{2}$.

What is the asymptotic distribution of 
$$
\sum_{i=1}^{n} X_i
$$


- [ ] $N(\mu,\sigma^{2})$
- [ ] $N(\mu,\sigma^{2}/n)$
- [ ] $N(n \mu, n \sigma^{2})$
- [ ] $\Gamma(\mu,\sigma^{2}/n)$
:::


::: {.callout-tip}
## Solution
:::

::: {#exr-05-sample-mean}
Let $X_{1}, X_{2}, \ldots, X_{n}$ 
be a random sample from  a distribution with pdf
$$
f(x) = \theta x^{\theta-1} \, I_{(0,1)}(x)
$$

To what does the sample mean $\overline{X}$ converge in probability?

- [ ] 0
- [ ] $\frac{\theta}{\theta+1}$
- [ ] $\theta$
- [ ] $1+\frac{1}{\theta}$
:::

::: {.callout-tip}
## Solution
:::