project:
  type: book
  preview:
    port: 4302 # increment port number for each course

#prefer-html: true

google-analytics: 
  tracking-id: "G-GYZ17VPVEJ"
  anonymize-ip: true

book:
  title: "Statistical Estimation for Data Science & AI"
  author: "Oren Bochman"
  date: "12/4/2025"  
  page-footer: 
    left: "Copyright 2026, Oren Bochman" 
    right: 
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/OrenBochman/c2-statistical-inference--for-estimation-in-data-science
          - text: Report a Bug
            url: https://github.com/OrenBochman/c2-statistical-inference--for-estimation-in-data-science/issues
      - icon: twitter 
        href: https://twitter.com/orenbochman 
      - icon: bi-house
        href: https://orenbochman.github.io/blog/
      - icon: linkedin 
        href: https://www.linkedin.com/li/orenbochman/

  chapters:
    - index.qmd
    - notes/intro.qmd
    - notes/summary.qmd
    - notes/01_welcome-to-the-course/index.qmd
    - part: "Module 2 Point Estimation"
      chapters:
      - notes/02_point-estimation/01_lesson-1-review-of-discrete-and-continuous-random-variables/index.qmd
      - notes/02_point-estimation/02_lesson-2-joint-distributions/index.qmd
      - notes/02_point-estimation/03_lesson-3-the-gamma-distribution/index.qmd
      - notes/02_point-estimation/04_lesson-4-transformations-of-distributions/index.qmd
      - notes/02_point-estimation/05_lesson-5-expectation-and-properties-of-expectation/index.qmd
      - notes/02_point-estimation/_probability-expectation-and-variance.qmd
      - notes/02_point-estimation/06_lesson-6-variance-and-covariance/index.qmd
      - notes/02_point-estimation/07_lesson-7-estimators-and-sampling-distributions/index.qmd
      - notes/02_point-estimation/08_lesson-8-distributions-of-sums/index.qmd
      - notes/02_point-estimation/09_lesson-9-method-of-moments-estimators/index.qmd
      - notes/02_point-estimation/_the-shape-of-data.qmd
    - part: "Module 3 Maximum Likelihood Estimation"
      chapters:
      - notes/03_maximum-likelihood-estimation/01_lesson-1-a-motivating-example/index.qmd      
      - notes/03_maximum-likelihood-estimation/02_lesson-2-notation-terminology-and-first-complete-examples/index.qmd
      - notes/03_maximum-likelihood-estimation/03_lesson-3-multiple-parameters-and-parameters-in-the-support-of-a-distribution/index.qmd
      - notes/03_maximum-likelihood-estimation/_finding-mles.qmd
      - notes/03_maximum-likelihood-estimation/04_lesson-4-the-invariance-property-of-maximum-likelihood-estimators/index.qmd
      - notes/03_maximum-likelihood-estimation/SamplingDistributions.ipynb
      - notes/03_maximum-likelihood-estimation/05_lesson-5-mean-squared-error-bias-and-relative-efficiency/index.qmd
      - notes/03_maximum-likelihood-estimation/_invariance-mean-squared-error-and-efficiency.qmd
      - notes/03_maximum-likelihood-estimation/SamplingDistributions.ipynb
    - part: "Module 4 Large Sample Properties of Maximum Likelihood Estimators"
      chapters: 
      - notes/04_large-sample-properties-of-maximum-likelihood-estimators/01_lesson-1-fisher-information-and-the-cramer-rao-lower-bound/index.qmd
      - notes/04_large-sample-properties-of-maximum-likelihood-estimators/02_lesson-2-computational-simplifications-for-the-cramer-rao-lower-bound/index.qmd
      - notes/04_large-sample-properties-of-maximum-likelihood-estimators/03_lesson-3-convergence-for-sequences-of-random-variables/index.qmd
      - notes/04_large-sample-properties-of-maximum-likelihood-estimators/04_lesson-4-the-central-limit-theorem/index.qmd
      - notes/04_large-sample-properties-of-maximum-likelihood-estimators/05_lesson-5-properties-of-maximum-likelihood-estimators/index.qmd

    - part: "Module 5 Large Sample Properties of Maximum Likelihood Estimators"
      chapters: 
      - notes/05_confidence-intervals-involving-the-normal-distribution/01_lesson-1-a-normal-introduction-to-confidence-intervals/index.qmd
      - notes/05_confidence-intervals-involving-the-normal-distribution/02_lesson-2-the-t-and-chi-squared-distributions-and-the-sample-variance/index.qmd
      - notes/05_confidence-intervals-involving-the-normal-distribution/03_lesson-3-one-sample-confidence-intervals-based-on-the-t-distribution/index.qmd
      - notes/05_confidence-intervals-involving-the-normal-distribution/04_lesson-4-two-sample-confidence-intervals-for-means/index.qmd
      - notes/05_confidence-intervals-involving-the-normal-distribution/05_lesson-5-small-population-confidence-intervals-for-differences-in-means/index.qmd

    - part: "Module 6 beyond normality confidence intervals unleashed"
      chapters: 
      - notes/06_beyond-normality-confidence-intervals-unleashed/01_lesson-1-a-confidence-interval-for-proportions/index.qmd
      - notes/06_beyond-normality-confidence-intervals-unleashed/02_lesson-2-confidence-intervals-for-variances-and-a-difference-of-propoertions/index.qmd
      - notes/06_beyond-normality-confidence-intervals-unleashed/03_lesson-3-a-confidence-interval-for-a-ratio-of-variances/index.qmd
      - notes/06_beyond-normality-confidence-intervals-unleashed/04_lesson-4-general-confidence-intervals/index.qmd
      - notes/06_beyond-normality-confidence-intervals-unleashed/05_lesson-5-general-confidence-intervals-2/index.qmd

    - notes/references.qmd
bibliography: references.bib

format:
  html:
    from: markdown+emoji
    css: styles.css
    theme:
      light: [cosmo, theme.scss, custom.scss]
      dark: [cosmo, theme-dark.scss, custom.scss]
    lightbox: true
    html-math-method: 
      method: katex
      options:
        fleqn: true

    toc: true
    toc-location: left

  # pdf:
  #   documentclass: scrreprt
  #   lof: true
  #   lot: true
  #   include-in-header:
  #     - text: |
  #         \usepackage{cancel}
  # epub:
  #   cover-image: cover.png

execute: 
  freeze: auto
  cache: true
