
## Chapter 9. Hypothesis Testing with One Sample

### Section 1. Null and Alternative Hypotheses

TRY IT 9.1
A medical trial is conducted to test whether or not a new medicine reduces cholesterol by 25%. State the null and alternative hypotheses.
Solution:
H0 : The drug reduces cholesterol by 25%.  = 0.25
Ha : The drug does not reduce cholesterol by 25%.  ≠ 0.25
TRY IT 9.2
We want to test whether the mean height of eighth graders is 66 inches. State the null and alternative hypotheses. Fill in the correct symbol (=, ≠, ≥, <, ≤, >) for the null and alternative hypotheses.
    a. H0: μ __ 66
    b. Ha: μ __ 66
Solution:
    a. H0 : μ = 66
    b. Ha : μ ≠ 66
TRY IT 9.3
We want to test if it takes fewer than 45 minutes to teach a lesson plan. State the null and alternative hypotheses. Fill in the correct symbol ( =, ≠, ≥, <, ≤, >) for the null and alternative hypotheses.

a. H0: μ __ 45
b. Ha: μ __ 45
Solution:

a. H0: μ ≥ 45
b. Ha: μ < 45

TRY IT 9.4

On a state driver’s test, about 40% pass the test on the first try. We want to test if more than 40% pass on the first try. Fill in the correct symbol (=, ≠, ≥, <, ≤, >) for the null and alternative hypotheses.

a. H0: p __ 0.40
b. Ha: p __ 0.40

Solution:

a. H0: p = 0.40
b. Ha: p > 0.40

TRY IT 9.5
Suppose the null hypothesis, H0, is: the blood cultures contain no traces of pathogen X. State the Type I and Type II errors.
Solution:
Type I error: The researcher thinks the blood cultures do contain traces of pathogen X, when in fact, they do not.
Type II error: The researcher thinks the blood cultures do not contain traces of pathogen X, when in fact, they do.
TRY IT 9.6
Suppose the null hypothesis, H0, is: a patient is not sick. Which type of error has the greater consequence, Type I or Type II?
Solution:
The error with the greater consequence is the Type II error: the patient will be thought well when, in fact, he is sick, so he will not get treatment.
TRY IT 9.7
“Red tide” is a bloom of poison-producing algae–a few different species of a class of plankton called dinoflagellates. When the weather and water conditions cause these blooms, shellfish such as clams living in the area develop dangerous levels of a paralysis-inducing toxin. In Massachusetts, the Division of Marine Fisheries (DMF) monitors levels of the toxin in shellfish by regular sampling of shellfish along the coastline. If the mean level of toxin in clams exceeds 800 μg (micrograms) of toxin per kg of clam meat in any area, clam harvesting is banned there until the bloom is over and levels of toxin in clams subside. Describe both a Type I and a Type II error in this context, and state which error has the greater consequence.
Solution:
In this scenario, an appropriate null hypothesis would beH0: the mean level of toxins is at most 800 μg, H0 : μ0 ≤ 800 μg.
Type I error: The DMF believes that toxin levels are still too high when, in fact, toxin levels are at most 800 μg. The DMF continues the harvesting ban.
Type II error: The DMF believes that toxin levels are within acceptable levels (are at least 800 μg) when, in fact, toxin levels are still too high (more than 800 μg). The DMF lifts the harvesting ban. This error could be the most serious. If the ban is lifted and clams are still toxic, consumers could possibly eat tainted food.
In summary, the more dangerous error would be to commit a Type II error, because this error involves the availability of tainted clams for consumption.
TRY IT 9.8
Determine both Type I and Type II errors for the following scenario:
Assume a null hypothesis, H0, that states the percentage of adults with jobs is at least 88%.
Identify the Type I and Type II errors from these four statements.
    a. Not to reject the null hypothesis that the percentage of adults who have jobs is at least 88% when that percentage is actually less than 88%
    b. Not to reject the null hypothesis that the percentage of adults who have jobs is at least 88% when the percentage is actually at least 88%.
    c. Reject the null hypothesis that the percentage of adults who have jobs is at least 88% when the percentage is actually at least 88%.
    d. Reject the null hypothesis that the percentage of adults who have jobs is at least 88% when that percentage is actually less than 88%.
Solution:
Type I error: c
Type I error: a
Section 4. Rare Events, the Sample, Decision and Conclusion

TRY IT 9.9
A normal distribution has a standard deviation of 1. We want to verify a claim that the mean is greater than 12. A sample of 36 is taken with a sample mean of 12.5.
H0: μ ≤ 12 
Ha: μ > 12 
The p-value is 0.0013 
Draw a graph that shows the p-value.
Solution:
p-value = 0.0013

                                            Figure 18
TRY IT 9.10
It’s a Boy Genetics Labs claim their procedures improve the chances of a boy being born. The results for a test of a single population proportion are as follows:
H0: p = 0.50, Ha: p > 0.50
α = 0.01
p-value = 0.025
Interpret the results and state a conclusion in simple, non-technical terms.
Solution:
Since the p-value is greater than the established alpha value (the p-value is high), we do not reject the null hypothesis. There is not enough evidence to support It’s a Boy Genetics Labs' stated claim that their procedures improve the chances of a boy being born.
Section 5. Additional Information and Full Hypothesis Test Examples

TRY IT 9.11
H0: μ = 10, Ha: μ < 10
Assume the p-value is 0.0935. What type of test is this? Draw the picture of the p-value.
Solution:
left-tailed test

                                             Figure 19
TRY IT 9.12
H0: μ ≤ 1, Ha: μ > 1
Assume the p-value is 0.1243. What type of test is this? Draw the picture of the p-value.
Solution:
right-tailed test

                                               Figure 20
TRY IT 9.13
H0: p = 0.5, Ha: p ≠ 0.5
Assume the p-value is 0.2564. What type of test is this? Draw the picture of the p-value.
Solution:
two-tailed test

                                                Figure 21
TRY IT 9.14
The mean throwing distance of a football for Marco, a high school quarterback, is 40 yards, with a standard deviation of two yards. The team coach tells Marco to adjust his grip to get more distance. The coach records the distances for 20 throws. For the 20 throws, Marco’s mean distance was 45 yards. The coach thought the different grip helped Marco throw farther than 40 yards. Conduct a hypothesis test using a preset α = 0.05. Assume the throw distances for footballs are normal.
First, determine what type of test this is, set up the hypothesis test, find the p-value, sketch the graph, and state your conclusion.
Solution:
Since the problem is about a mean, this is a test of a single population mean.
H0 : μ = 40
Ha : μ > 40
p = 2.6115 × 10–29

    			  Figure 22
Because p < α, we reject the null hypothesis. There is sufficient evidence to suggest that the change in grip improved Marco’s throwing distance.

TRY IT 9.15
A company records the mean time of employees working in a day. The mean comes out to be 475 minutes, with a standard deviation of 45 minutes. A manager recorded times of 20 employees. The times of working were (frequencies are in parentheses) 460(3); 465(2); 470(3); 475(1); 480(6); 485(3); 490(2). 
Conduct a hypothesis test using a 2.5% level of significance to determine if the mean time is more than 475. 
Solution:
Set up the Hypothesis Test: 
 
 
This is a right-tailed test. The random variable is the mean time of employees working in a day. 
Distribution for the test: is known. 
 
minutes (from the data). 
minutes. We assume minutes unless our data shows otherwise. 
The p-value is calculated: 
p-value =  
Interpretation of p-value: If is true, then there is a 0.5044, or 50.44%, chance that the mean time of employees working is 475.5 minutes or more. Since a 50.44% chance is large enough, the mean time of 475.5 is not a rare event. 
Compare and p values: 
and  
Make a decision: Since value, do not reject . 
Conclusion: At the 2.5% level of significance, from the sample data, there is not sufficient evidence to conclude that the true mean time of employees is more than 475 minutes.
TRY IT 9.16
It is believed that a stock price for a particular company will grow at a rate of $5 per week with a standard deviation of $1. An investor believes the stock won’t grow as quickly. The changes in stock price is recorded for ten weeks and are as follows: $4, $3, $2, $3, $1, $7, $2, $1, $1, $2. Perform a hypothesis test using a 5% level of significance. State the null and alternative hypotheses, find the p-value, state your conclusion, and identify the Type I and Type II errors.
Solution:
H0: μ = 5
Ha: μ < 5
p = 0.0082
Because p < α, we reject the null hypothesis. There is sufficient evidence to suggest that the stock price of the company grows at a rate less than $5 a week.
Type I Error: To conclude that the stock price is growing slower than $5 a week when, in fact, the stock price is growing at $5 a week (reject the null hypothesis when the null hypothesis is true).
Type II Error: To conclude that the stock price is growing at a rate of $5 a week when, in fact, the stock price is growing slower than $5 a week (do not reject the null hypothesis when the null hypothesis is false).
TRY IT 9.17
A teacher believes that 85% of students in the class will want to go on a field trip to the local zoo. They perform a hypothesis test to determine if the percentage is the same or different from 85%. The teacher samples 50 students and 39 reply that they would want to go to the zoo. For the hypothesis test, use a 1% level of significance.
First, determine what type of test this is, set up the hypothesis test, find the p-value, sketch the graph, and state your conclusion.
Solution:
Since the problem is about percentages, this is a test of single population proportions.
H0 : p = 0.85
Ha: p ≠ 0.85
p = 0.1657

 			   Figure 23
Because p > α, we fail to reject the null hypothesis. There is not sufficient evidence to suggest that the proportion of students that want to go to the zoo is not 85%.
TRY IT 9.18
Marketers believe that 92% of adults in the United States own a cell phone. A cell phone manufacturer believes that number is actually lower. 200 American adults are surveyed, of which, 174 report having cell phones. Use a 5% level of significance. State the null and alternative hypothesis, find the p-value, state your conclusion, and identify the Type I and Type II errors.
Solution:
H0: p = 0.92
Ha: p < 0.92
p-value = 0.0046
Because p < 0.05, we reject the null hypothesis. There is sufficient evidence to conclude that fewer than 92% of American adults own cell phones.
Type I Error: To conclude that fewer than 92% of American adults own cell phones when, in fact, 92% of American adults do own cell phones (reject the null hypothesis when the null hypothesis is true).
Type II Error: To conclude that 92% of American adults own cell phones when, in fact, fewer than 92% of American adults own cell phones (do not reject the null hypothesis when the null hypothesis is false).
TRY IT 9.19
A car soap gets rid of 30% of stains on the car. After adding a new compound to the soap, the soap is used on a car and found to wash 20 stains out of the 50 stains on the car. With the level of significance being 0.01, find out if adding the new compound to soap is beneficial.
Solution:
Set up hypothesis test: 
		 
The distribution to use for the test is: 
Normal:  
The test statistic is obtained to be z = 1.543. 
The p-value is obtained to be p = 0.0614. 
If the null hypothesis is true, then there is a 0.0614 probability that the sample proportion is 0.4 or more. 
At 1% level of significance, the value of is less than the p-value. So, the data does not show sufficient evidence that the percentage of stains removed is more than 30%. 
The confidence interval is obtained as (0.273, 0.527). 
TRY IT 9.20
The boiling point of a specific liquid is measured for 15 samples, and the boiling points are obtained as follows: 
205; 206; 206; 202; 199; 194; 197; 198; 198; 201; 201; 202; 207; 211; 205 
Is there convincing evidence that the average boiling point is greater than 200? Use a significance level of 0.1. Assume the population is normal. 
Solution:
The hypotheses, at a significance level of 0.1, will be as follows: 
    a.  
    b.  
Since the standard deviation is not known, Student’s t-distribution is to be used. 
The data is input into the TI-83 as follows: 
 

 

 

 
 
Since the p-value is less than alpha value, we will reject the null hypothesis. It is reasonable to state that the data supports the claim that the average boiling point is greater than 200. 
TRY IT 9.21
In a study of 390,000 moisturizer users, 138 of the subjects developed skin diseases. Test the claim that moisturizer users developed skin diseases at a greater rate than that for non-moisturizer users (the rate of skin diseases for non-moisturizer users is 0.041%). Since this is a critical issue, use a 0.005 significance level. Explain why the significance level should be so low in terms of a Type I error. 
Solution:
The test hypotheses are as follows: 
    a.  
    b.  
If we commit a Type I error, we are essentially accepting a false claim. Since the claim describes disease-causing environments, we want to minimize the chances of incorrectly identifying causes of diseases. 
The testing will be done with x = 138 and n = 390,000. The sample is sufficiently large because we have np = 390,000(0.00041) = 159.9, nq = 390,000(0.99959) = 389,840.1, two independent outcomes, and a fixed probability of success p = 0.00041. Thus, we will be able to generalize our results to the population. 
The associated TI results are: 

 
 

 
Since the p-value = 0.0832 is greater than alpha value = 0.005, we cannot reject the null. Therefore, we conclude that there is not enough evidence to support the claim of higher skin diseases rates for moisturizer users. 
TRY IT 9.22
According to the U.S. Census, there are approximately 201,456,463 residents 20 and older. Statistics from the Criminal National Network indicate that, on average, 104,354 murders occur each year for people aged 20 and older. This translates into a percentage of murder of 0.052%. In Ohio, there were reported 127 murders for a population of 427,648. Conduct an appropriate hypothesis test to determine if there is a statistically significant difference between the local murder percentage and the national murder percentage. Use a significance level of 0.01. 
Solution:
The hypotheses for the one-proportion z-test are as follow: 
    a.  
    b.  
The following screenshots display the summary statistics from the hypothesis test: 

 

 
 
Since the p-value = 0 is less than alpha value of 0.01, the sample data includes that we should reject the null hypothesis. In conclusion, the sample data support the claim that the proportion of murders in Ohio is different from the national average population. 
Chapter 10. Hypothesis Testing with Two Samples
Section 1. Two Population Means with Unknown Standard Deviations

TRY IT 10.1
Two samples are shown in Table 10.2. Both have normal distributions. The means for the two populations are thought to be the same. Is there a difference in the means? Test at the 5% level of significance.

| | Sample Size | Sample Mean | Sample Standard Deviation |
|---|---:|---:|---:|
| Population A | 25 | 5 | 1 |
| Population B | 16 | 4.7 | 1.2 |

: Table 10.2

Solution:
The p-value is 0.4125, which is much higher than 0.05, so we decline to reject the null hypothesis. There is not sufficient evidence to conclude that the means of the two populations are not the same.
TRY IT 10.2
A study is done to determine if Company A retains its workers longer than Company B. Company A samples 15 workers, and their average time with the company is five years with a standard deviation of 1.2. Company B samples 20 workers, and their average time with the company is 4.5 years with a standard deviation of 0.8. The populations are normally distributed.
    a. Are the population standard deviations known?
    b. Conduct an appropriate hypothesis test. At the 5% significance level, what is your conclusion?
Solution:
    a. They are unknown.
    b. The p-value = 0.0878. At the 5% level of significance, there is insufficient evidence to conclude that the workers of Company A stay longer with the company.
try it 10.3
Two professors, A and B, teach classes on the same subjects. Scores of 10 students from each class are selected randomly. The final exam scores of the students are as follows: 
Professor A: 
97 
62 
73 
58 
84 
74 
66 
93 
73 
85 
 
Professor B: 
85 
64 
74 
55 
76 
67 
72 
84 
71 
98 
 
Professor A says that the mean score of their class is more than the mean of professor B’s class. Is professor A correct? Test at a 5% significance level. Answer the following questions: 

a. Is this a test of two means or two proportions? 
b. Are the population standard deviations known or unknown? 
c. Which distribution do you use to perform the test? 
d. What is the random variable? 
e. What are the null and alternative hypotheses? Write the null and alternative hypotheses in words and in symbols. 
f. Is this test right-, left-, or two-tailed? 
g. What is the p-value? 
h. Do you reject or not reject the null hypothesis? 
i. At the ___ level of significance, from the sample data, there ___ (is/is not) sufficient evidence to conclude that ___. 

solution:

a. two means 
b. unknown 
c. Student’s t 
d.  
e. 
    1. Null hypothesis: the means of final exam scores are equal for both professors. 
    2. Alternative hypothesis: the mean of final exam scores for class of professor B is less than mean of final exam scores for class of professor A. 
f. left-tailed 
g. p-value = 0.03 
h. Reject the null hypothesis. 
i. Professor A is correct. The evidence shows that the mean of final exam scores of the class of professor A is more than that of the class of professor B. 

At the 5% level of significance, from the sample data, there is (is/is not) sufficient evidence to conclude that the mean of final exam scores of the class of professor A is more than that of the class of professor B. 

try it 10.4
Calculate Cohen’s d for Try It 10.4. Is the size of the effect small, medium, or large? Explain what the size of the effect means for this problem.

Solution:
     
     
d = 0.49 
The effect is medium because 0.49 is very close to Cohen’s value of 0.5 for medium effect size. The size of the differences of the means for the two companies is small, indicating that there is not a significant difference between them. 


TRY IT 10.5

Weighted alpha is a measure of risk-adjusted performance of stocks over a period of a year. A high positive weighted alpha signifies a stock whose price has risen while a small positive weighted alpha indicates an unchanged stock price during the time period. Weighted alpha is used to identify companies with strong upward or downward trends. The weighted alpha for the top 30 stocks of banks in the northeast and in the west as identified by Nasdaq on May 24, 2013 are listed in Table 10.8 and Table 10.9, respectively.

| A    | B    | C    | D    | E    | F    |
|------|------|------|------|------|------|
| 94.2 | 75.2 | 69.6 | 52.0 | 48.0 | 41.9 |
| 36.4 | 33.4 | 31.5 | 27.6 | 77.3 | 71.9 |
| 67.5 | 50.6 | 46.2 | 38.4 | 35.2 | 33.0 |
| 28.7 | 26.5 | 76.3 | 71.7 | 56.3 | 48.7 |
| 43.2 | 37.6 | 33.7 | 31.8 | 28.5 | 26.0 |

: Table 10.8 Northeast

| A     | B    | C    | D    | E     | F    |
|-------|------|------|------|-------|------|
| 126.0 | 70.6 | 65.2 | 51.4 | 45.5  | 37.0 |
| 33.0  | 29.6 | 23.7 | 22.6 | 116.1 | 70.6 |
| 58.2  | 51.2 | 43.2 | 36.0 | 31.4  | 28.7 |
| 23.5  | 21.6 | 78.2 | 68.2 | 55.6  | 50.3 |
| 39.0  | 34.1 | 31.0 | 25.3 | 23.4  | 21.5 |

: Table 10.8 West

Is there a difference in the weighted alpha of the top 30 stocks of banks in the northeast and in the west? Test at a 5% significance level. Answer the following questions:
    a. Is this a test of two means or two proportions?
    b. Are the population standard deviations known or unknown?
    c. Which distribution do you use to perform the test?
    d. What is the random variable?
    e. What are the null and alternative hypotheses? Write the null and alternative hypotheses in words and in symbols.
    f. Is this test right, left, or two tailed?
    g. What is the p-value?
    h. Do you reject or not reject the null hypothesis?
    i. At the ___ level of significance, from the sample data, there ______ (is/is not) sufficient evidence to conclude that ______.
    j. Calculate Cohen’s d and interpret it.
Solution:
    a. two means
    b. unknown
    c. Student’s-t
    d. X̄ 1 - X̄ 2
    e. 
        1. H0 : μ1 = μ2 Null hypothesis: the means of the weighted alphas are equal.
        2. Ha : μ1 ≠ μ2 Alternative hypothesis : the means of the weighted alphas are not equal.
    f. two-tailed
    g. p-value = 0.8787
    h. Do not reject the null hypothesis
    i. This indicates that the trends in stocks are about the same in the top 30 banks in each region.
5% level of significance, from the sample data, there is not sufficient evidence to conclude that the mean weighted alphas for the banks in the northeast and the west are different
    j. d = 0.040, Very small, because 0.040 is less than Cohen’s value of 0.2 for small effect size. The size of the difference of the means of the weighted alphas for the two regions of banks is small indicating that there is not a significant difference between their trends in stocks.
Section 2. Two Population Means with Known Standard Deviations

TRY IT 10.6
The means of the number of revolutions per minute of two competing engines are to be compared. Thirty engines of each type are randomly assigned to be tested. Both populations have normal distributions. Table 10.11 shows the result. Do the data indicate that Engine 2 has higher RPM than Engine 1? Test at a 5% level of significance.
| Engine | Sample Mean Number of RPM | Population Standard Deviation |
|--------|---------------------------|------------------------------|
| 1      | 1,500                     | 50                           |
| 2      | 1,600                     | 60                           |

: Table 10.11
Solution:
The p-value is almost zero, so we reject the null hypothesis. There is sufficient evidence to conclude that Engine 2 runs at a higher RPM than Engine 1.
TRY IT 10.7
The average age of 10 professors selected randomly in university A is 46.672 with a standard deviation of 8.53. The average age of 10 professors selected randomly in university B is 47.531 with a standard deviation of 7.83. 
Does the data indicate that university A has older professors than university B, on average? Test at a 5% level of significance. 
Solution:
The total sample size is 10 + 10 = 20., which is greater than 10, so we can use the Student’s t-distribution. 
The random variable is = difference between the mean age of universities A and B. 
	 
	 
The phrase “older than” translates as a “>” symbol and goes into . Therefore, this is a right-tailed test. 
The distribution is:  
The mean for the normal distribution is 0 since and . 
The p-value is obtained as 0.4258. Since alpha is less than the p-value, do not reject the . 
At the 5% level of significance, from the sample data, there is not sufficient evidence to conclude that the mean age of professors in university A is more than the mean age of professors in university B. 

Section 3. Comparing Two Independent Population Proportions

TRY IT 10.8
Two types of valves are being tested to determine if there is a difference in pressure tolerances. Fifteen out of a random sample of 100 of Valve A cracked under 4,500 psi. Six out of a random sample of 100 of Valve B cracked under 4,500 psi. Test at a 5% level of significance.
Solution:
The p-value is 0.0379, so we can reject the null hypothesis. At the 5% significance level, the data support that there is a difference in the pressure tolerances between the two valves.

TRY IT 10.9
A survey was conducted about the favorable beverage as tea. The data collected is summarized in the table. Is the proportion of males favoring tea more than females favoring tea? Test at a 1% level of significance. 
 
|              | Male | Female |
|--------------|------|--------|
| Favor tea    | 16   | 18     |
| Total surveyed | 230  | 218    |

Solution:
Let and be desired population proportions. 
 
 
The test is for “less than,” so it is left-tailed. 
Distribution for the test: 
 
 
 
This follows an approximate normal distribution. 
Calculate the p-value using the normal distribution: 
p-value = 0.1023 
Decision: Since , do not reject . 
Conclusion: At 1% level of significance, from the sample data, there is not sufficient evidence to conclude that the proportion of females favoring tea is less than the proportion of males favoring tea. 


TRY IT 10.10
A government researcher is investigating whether there is a difference in the use of helmets by motorcyclists in different geographic regions for those states where use of helmets is required by law. The research shows that for motorcyclists in the northeast U.S., 7622 out of 113,231 motorcyclists did not wear helmets. In the southeast U.S., 7439 out of 104,873 motorcyclists did not wear helmets. Test at a 5% significance level. Answer the following questions:
a. Is this a test of two means or two proportions?
b. Which distribution do you use to perform the test?
c. What is the random variable?
d. What are the null and alternative hypothesis? Write the null and alternative hypothesis in symbols.
e. Is this test right-, left-, or two-tailed?
f. What is the p-value?
g. Do you reject or not reject the null hypothesis?
h. At the ___ level of significance, from the sample data, there ______ (is/is not) sufficient evidence to conclude that ____________.
Solution:
a. two proportions
b. normal for two proportions
c. Subscripts: 1 = Northeast, 2 = Southeast 
P′2 - P′2
d. Subscripts: 1 = Northeast, 2 = Southeast
H0: p1 = p2 H0: p1 − p2 = 0 
Ha: p1 ≠ p2 Ha: p1 − p2 ≠ 0
e. two-tailed
f. p-value = 0.00086

			Figure 24
g. Reject the H0.
h. At the 5% significance level, from the sample data, there is sufficient evidence to conclude that there is a difference between the proportion of motorcyclists who did not wear helmets for northeast and southeast regions of the U.S.
Section 4. Matched or Paired Samples

TRY IT 10.11
A study was conducted to investigate how effective a new diet was in lowering cholesterol. Results for the randomly selected subjects are shown in the table. The differences have a normal distribution. Are the subjects’ cholesterol levels lower on average after the diet? Test at the 5% level.

| Subject | A   | B   | C   | D   | E   | F   | G   | H   | I   |
|---------|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| Before  | 209 | 210 | 205 | 198 | 216 | 217 | 238 | 240 | 222 |
| After   | 199 | 207 | 189 | 209 | 217 | 202 | 211 | 223 | 201 |

: Table 10.16

Solution:
The p-value is 0.0130, so we can reject the null hypothesis. There is enough evidence to suggest that the diet lowers cholesterol.
TRY IT 10.12
A new prep class was designed to improve SAT test scores. Five students were selected at random. Their scores on two practice exams were recorded, one before the class and one after. The data recorded in Table 10.18. Are the scores, on average, higher after the class? Test at a 5% level.

| SAT Scores         | Student 1 | Student 2 | Student 3 | Student 4 |
|-------------------|-----------|-----------|-----------|-----------|
| Score before class | 1840      | 1960      | 1920      | 2150      |
| Score after class  | 1920      | 2160      | 2200      | 2100      |

: Table 10.18

Solution:
The p-value is 0.0874, so we decline to reject the null hypothesis. The data do not support that the class improves SAT scores significantly.
TRY IT 10.13
Five ball players think they can throw the same distance with their dominant hand (throwing) and off-hand (catching hand). The data were collected and recorded in Table 10.20. Conduct a hypothesis test to determine whether the mean difference in distances between the dominant and off-hand is significant. Test at the 5% level.

|            | Player 1 | Player 2 | Player 3 | Player 4 | Player 5 |
|------------|----------|----------|----------|----------|----------|
| Dominant Hand | 120      | 111      | 135      | 140      | 125      |
| Off-hand      | 105      | 109      | 98       | 111      | 99       |

: Table 10.20
Solution:
The p-level is 0.0230, so we can reject the null hypothesis. The data show that the players do not throw the same distance with their off-hands as they do with their dominant hands.
Chapter 11. The Chi-Square Distribution
Section 2. Goodness-of-Fit Test

TRY IT 11.1
A factory manager needs to understand how many products are defective versus how many are produced. The number of expected defects is listed in Table 11.5.

| Number produced | Number defective |
|---|---:|
| 0–100 | 5 |
| 101–200 | 6 |
| 201–300 | 7 |
| 301–400 | 8 |
| 401–500 | 10 |

: Table 11.5

A random sample was taken to determine the actual number of defects. Table 11.6 shows the results of the survey.

| Number produced | Number defective |
|---|---:|
| 0–100 | 5 |
| 101–200 | 7 |
| 201–300 | 8 |
| 301–400 | 9 |
| 401–500 | 11 |

: Table 11.6

State the null and alternative hypotheses needed to conduct a goodness-of-fit test, and state the degrees of freedom.
Solution:
H0:The number of defaults fits expectations.
Ha:The number of defaults does not fit expectations.
df = 4
TRY IT 11.2
Teachers want to know which night each week their students are doing most of their homework. Most teachers think that students do homework equally throughout the week. Suppose a random sample of 56 students were asked on which night of the week they did the most homework. The results were distributed as in Table 11.8.

| | Sunday | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday |
|---|---:|---:|---:|---:|---:|---:|---:|
| Number of Students | 11 | 8 | 10 | 7 | 10 | 5 | 5 |

: Table 11.8

From the population of students, do the nights for the highest number of students doing the majority of their homework occur with equal frequencies during a week? What type of hypothesis test should you use?
Solution:
df = 6
p-value = 0.6093 
We decline to reject the null hypothesis. There is not enough evidence to support that students do not do the majority of their homework equally throughout the week.
TRY IT 11.3
The expected percentage of the number of pets students have in their homes is distributed (this is the given distribution for the student population of the United States) as in Table 11.12.

| Number of Pets | Percent |
|---|---:|
| 0 | 18 |
| 1 | 25 |
| 2 | 30 |
| 3 | 18 |
| 4+ | 9 |

: Table 11.12

A random sample of 1,000 students from the Eastern United States resulted in the data in Table 11.13.

| Number of Pets | Frequency |
|---|---:|
| 0 | 210 |
| 1 | 240 |
| 2 | 320 |
| 3 | 140 |
| 4+ | 90 |

: Table 11.13

At the 1% significance level, does it appear that the distribution “number of pets” of students in the Eastern United States is different from the distribution for the United States student population as a whole? What is the p-value?
Solution:
p-value = 0.0036
We reject the null hypothesis that the distributions are the same. There is sufficient evidence to conclude that the distribution “number of pets” of students in the Eastern United States is different from the distribution for the United States student population as a whole.
TRY IT 11.4
Students in a social studies class hypothesize that the literacy rates across the world for every region are 82%. Table 11.14 shows the actual literacy rates across the world broken down by region. What are the test statistic and the degrees of freedom?

| MDG Region | Adult Literacy Rate (%) |
|---|---:|
| Developed Regions | 99.0 |
| Commonwealth of Independent States | 99.5 |
| Northern Africa | 67.3 |
| Sub-Saharan Africa | 62.5 |
| Latin America and the Caribbean | 91.0 |
| Eastern Asia | 93.8 |
| Southern Asia | 61.9 |
| South-Eastern Asia | 91.9 |
| Western Asia | 84.5 |
| Oceania | 66.4 |

: Table 11.14

Solution:
degrees of freedom = 9
chi2 test statistic = 26.38

Figure 25
Press STAT and ENTER. Make sure you clear lists L1, L2, and L3 if they have data in them. Into L1, put the observed frequencies 99, 99.5, 67.3, 62.5, 91, 93.8, 61.9, 91.9, 84.5, 66.4. Into L2, put the expected frequencies 82, 82, 82, 82, 82, 82, 82, 82, 82, 82. Arrow over to list L3 and up to the name area "L3". Enter (L1-L2)^2/L2and ENTER. Press 2nd QUIT. Press 2nd LIST and arrow over to MATH. Press 5. You should see "sum". Enter L3. Rounded to two decimal places, you should see 26.38. Press 2nd DISTR. Arrow down to 7:χ2cdf (or press 7). Press ENTER. Enter 26.38,1E99,9). Rounded to four places, you should see .0018, which is the p-value.
The newer TI-84 calculators have in STAT TESTS the test Chi2 GOF. To run the test, put the observed values (the data) into a first list and the expected values (the values you expect if the null hypothesis is true) into a second list. Press STAT TESTS and Chi2 GOF. Enter the list names for the Observed list and the Expected list. Enter the degrees of freedom and press calculate or draw. Make sure you clear any lists before you start.
Section 3. Test of Independence

TRY IT 11.5
A sample of 300 students is taken. Of the students surveyed, 50 were music students, while 250 were not. Ninety-seven were on the honor roll, while 203 were not. If we assume being a music student and being on the honor roll are independent events, what is the expected number of music students who are also on the honor roll?
Solution:
About 16 students are expected to be music students and on the honor roll.
TRY IT 11.6
The Bureau of Labor Statistics gathers data about employment in the United States. A sample is taken to calculate the number of U.S. citizens working in one of several industry sectors over time. Table 11.17 shows the results:

| Industry Sector | 2000 | 2010 | 2020 | Total |
|--------------------|---:|---:|---:|---:|
| Nonagriculture wage and salary | 13,243 | 13,044 | 15,018 | 41,305 |
| Goods-producing, excluding agriculture | 2,457 | 1,771 | 1,950 | 6,178 |
| Services-providing | 10,786 | 11,273 | 13,068 | 35,127 |
| Agriculture, forestry, fishing, and hunting | 240 | 214 | 201 | 655 |
| Nonagriculture self-employed and unpaid family worker | 931 | 894 | 972 | 2,797 |
| Secondary wage and salary jobs in agriculture and private household industries | 14 | 11 | 11 | 36 |
| Secondary jobs as a self-employed or unpaid family worker | 196 | 144 | 152 | 492 |
| Total | 27,867 | 27,351 | 31,372 | 86,590 |

: Table 11.17

We want to know if the change in the number of jobs is independent of the change in years. State the null and alternative hypotheses and the degrees of freedom.

Solution:
H0 : The number of jobs is independent of the year.
Ha : The number of jobs is dependent on the year.
df = 12

Press the MATRX key and arrow over to EDIT. Press 1:[A]. Press 3 ENTER 3 ENTER. Enter the table values by row. Press ENTER after each. Press 2nd QUIT. Press STATand arrow over to TESTS. Arrow down to C:χ2-TEST. Press ENTER. You should see Observed:[A] and Expected:[B]. Arrow down to Calculate. Press ENTER. The test statistic is 227.73 and the p−value = 5.90E - 42 = 0. Do the procedure a second time but arrow down to Draw instead of calculate.
TRY IT 11.7
Refer back to the information in Try It 11.6. How many service providing jobs are there expected to be in 2020? How many nonagriculture wage and salary jobs are there expected to be in 2020?
Solution:
12,727, 14,965
TRY IT 11.8
Do families and singles have the same distribution of cars? Use a level of significance of 0.05. Suppose that 100 randomly selected families and 200 randomly selected singles were asked what type of car they drove: sport, sedan, hatchback, truck, van/SUV. The results are shown in Table 11.20. Do families and singles have the same distribution of cars? Test at a level of significance of 0.05.

| | Sport | Sedan | Hatchback | Truck | Van/SUV |
|---|---:|---:|---:|---:|---:|
| Family | 5 | 15 | 35 | 17 | 28 |
| Single | 45 | 65 | 37 | 46 | 7 |

: Table 11.20

Solution:
With a p-value of almost zero, we reject the null hypothesis. The data show that the distribution of cars is not the same for families and singles.
TRY IT 11.9
Ivy League schools receive many applications, but only some can be accepted. At the schools listed in Table 11.22, two types of applications are accepted: regular and early decision.

| Application Type Accepted | Brown | Columbia | Cornell | Dartmouth | Penn | Yale |
|---|---:|---:|---:|---:|---:|---:|
| Regular | 2,115 | 1,792 | 5,306 | 1,734 | 2,685 | 1,245 |
| Early Decision | 577 | 627 | 1,228 | 444 | 1,195 | 761 |

: Table 11.22

We want to know if the number of regular applications accepted follows the same distribution as the number of early applications accepted. State the null and alternative hypotheses, the degrees of freedom and the test statistic, sketch the graph of the p-value, and draw a conclusion about the test of homogeneity.
Solution:
H0 : The distribution of regular applications accepted is the same as the distribution of early applications accepted.
Ha : The distribution of regular applications accepted is not the same as the distribution of early applications accepted. 
df = 5 
χ2 test statistic = 430.06

Figure 26
Press the MATRX key and arrow over to EDIT. Press 1:[A]. Press 3 ENTER 3 ENTER. Enter the table values by row. Press ENTER after each. Press 2nd QUIT. Press STAT and arrow over to TESTS. Arrow down toC:χ2-TEST. Press ENTER. You should see Observed:[A] and Expected:[B]. Arrow down to Calculate. Press ENTER. The test statistic is 430.06 and the p-value = 9.80E-91. Do the procedure a second time but arrow down to Draw instead of calculate.
Section 6. Test of a Single Variance

TRY IT 11.10
A SCUBA instructor wants to record the collective depths each of his students dives during their checkout. He is interested in how the depths vary, even though everyone should have been at the same depth. He believes the standard deviation is three feet. His assistant thinks the standard deviation is less than three feet. If the instructor were to conduct a test, what would the null and alternative hypotheses be?
Solution:
H0: σ2 = 32
Ha: σ2 < 32
TRY IT 11.11
The FCC conducts broadband speed tests to measure how much data per second passes between a consumer’s computer and the internet. At a certain point in time, the standard deviation of Internet speeds across Internet Service Providers (ISPs) was 12.2 percent. Suppose a sample of 15 ISPs is taken, and the standard deviation is 13.2. An analyst claims that the standard deviation of speeds is more than what was reported. State the null and alternative hypotheses, compute the degrees of freedom, the test statistic, sketch the graph of the p-value, and draw a conclusion. Test at the 1% significance level.
Solution:
H0: σ2 = 12.22
Ha: σ2 > 12.22 
df = 14 
chi2 test statistic = 16.39

The p-value is 0.2902, so we decline to reject the null hypothesis. There is not enough evidence to suggest that the variance is greater than 12.22.
In 2nd DISTR, use7:χ2cdf. The syntax is (lower, upper, df) for the parameter list. χ2cdf(16.39,10^99,14). The p-value = 0.2902.
Chapter 12. Linear Regression and Correlation
Section 1. Linear Equations

TRY IT 12.1
Is the following an example of a linear equation?
y = –0.125 – 3.5x
Solution:
Yes
TRY IT 12.2
Is the following an example of a linear equation? Why or why not?

                            Figure 12.3
Solution:
No, the graph is not a straight line; therefore, it is not a linear equation.
TRY IT 12.3
Emma’s Extreme Sports hires hang-gliding instructors and pays them a fee of $50 per class as well as $20 per student in the class. The total cost Emma pays depends on the number of students in a class. Find the equation that expresses the total cost in terms of the number of students in a class.
Solution:
y = 50 + 20x
TRY IT 12.4
Ethan repairs household appliances like dishwashers and refrigerators. For each visit, he charges $25 plus $20 per hour of work. A linear equation that expresses the total amount of money Ethan earns per visit is y = 25 + 20x.
What are the independent and dependent variables? What is the y-intercept and what is the slope? Interpret them using complete sentences.
Solution:
The independent variable (x) is the number of hours Ethan works each visit. The dependent variable (y) is the amount, in dollars, Ethan earns for each visit.
The y-intercept is 25 (a = 25). At the start of a visit, Ethan charges a one-time fee of $25 (this is when x = 0). The slope is 20 (b = 20). For each visit, Ethan earns $20 for each hour he works.
Section 2. Scatter Plots

TRY IT 12.5
Amelia plays basketball for her high school. She wants to improve to play at the college level. She notices that the number of points she scores in a game goes up in response to the number of hours she practices her jump shot each week. She records the following data:

| X (hours practicing jump shot) | Y (points scored in a game) |
|---:|---:|
| 5 | 15 |
| 7 | 22 |
| 9 | 28 |
| 10 | 31 |
| 11 | 33 |
| 12 | 36 |

: Table 12.2

Construct a scatter plot and state if what Amelia thinks appears to be true.
Solution:

Yes, Amelia’s assumption appears to be correct. The number of points Amelia scores per game goes up when she practices her jump shot more.
Section 3. The Regression Equation

TRY IT 12.6
SCUBA divers have maximum dive times they cannot exceed when going to different depths. The data in Table 12.4 show different depths with the maximum dive times in minutes. Use your calculator to find the least squares regression line and predict the maximum dive time for 110 feet.

| X (depth in feet) | Y (maximum dive time) |
|---:|---:|
| 50 | 80 |
| 60 | 55 |
| 70 | 45 |
| 80 | 35 |
| 90 | 25 |
| 100 | 22 |

: Table 12.4

Solution:
ŷ = 127.24 – 1.11x
At 110 feet, a diver could dive for only five minutes.
Section 4. Testing the Significance of the Correlation Coefficent

TRY IT 12.7
For a given line of best fit, you computed that r = 0.6501 using n = 12 data points and the critical value is 0.576. Can the line be used for prediction? Why or why not?
Solution:
If the scatter plot looks linear then, yes, the line can be used for prediction, because r > the positive critical value.
TRY IT 12.8
For a given line of best fit, you compute that r = 0.5204 using n = 9 data points, and the critical value is 0.666. Can the line be used for prediction? Why or why not?
Solution:
No, the line cannot be used for prediction, because r < the positive critical value.
TRY IT 12.9
For a given line of best fit, you compute that r = –0.7204 using n = 8 data points, and the critical value is = 0.707. Can the line be used for prediction? Why or why not?
Solution:
Yes, the line can be used for prediction, because r < the negative critical value.
TRY IT 12.10
For a given line of best fit, you compute that r = 0 using n = 100 data points. Can the line be used for prediction? Why or why not?
Solution:
No, the line cannot be used for prediction no matter what the sample size is.
Section 5. Prediction

TRY IT 12.11
Data are collected on the relationship between the number of hours per week practicing a musical instrument and scores on a math test. The line of best fit is as follows:
ŷ = 72.5 + 2.8x 
What would you predict the score on a math test would be for a student who practices a musical instrument for five hours a week?
Solution:
86.5
Section 6. Outliers

TRY IT 12.12
Identify the potential outlier in the scatter plot. The standard deviation of the residuals or errors is approximately 8.6.

Figure 12.19
Solution:
The outlier appears to be at (6, 58). The expected y value on the line for the point (6, 58) is approximately 82. Fifty-eight is 24 units from 82. Twenty-four is more than two standard deviations (2s = (2)(8.6) = 17.2 ). So 82 is more than two standard deviations from 58, which makes (6, 58) a potential outlier.
TRY IT 12.13
The data points for the graph from the third exam/final exam example are as follows: (1, 5), (2, 7), (2, 6), (3, 9), (4, 12), (4, 13), (5, 18), (6, 19), (7, 12), and (7, 21). Remove the outlier and recalculate the line of best fit. Find the value of ŷ when x = 10.
Solution:
ŷ = 1.04 + 2.96x; 30.64
TRY IT 12.14
The following table shows economic development measured in per capita income PCINC.

| Year | PCINC | Year | PCINC |
|---:|---:|---:|---:|
| 1870 | 340 | 1920 | 1050 |
| 1880 | 499 | 1930 | 1170 |
| 1890 | 592 | 1940 | 1364 |
| 1900 | 757 | 1950 | 1836 |
| 1910 | 927 | 1960 | 2132 |

: Table 12.7

    a. What are the independent and dependent variables?
    b. Draw a scatter plot.
    c. Use regression to find the line of best fit and the correlation coefficient.
    d. Interpret the significance of the correlation coefficient.
    e. Is there a linear relationship between the variables?
    f. Find the coefficient of determination and interpret it.
    g. What is the slope of the regression equation? What does it mean?
    h. Use the line of best fit to estimate PCINC for 1900, for 2000.
    i. Determine if there are any outliers.
Solution:
a. The independent variable (x) is the year and the dependent variable (y) is the per capita income.
b.

				               Figure 27
c. ŷ = 18.61x – 34574; r = 0.9732
d. At df = 8, the critical value is 0.632. The r value is significant because it is greater than the critical value.
e. There does appear to be a linear relationship between the variables.
f. The coefficient of determination is 0.947, which means that 94.7% of the variation in PCINC is explained by the variation in the years.
g. and h. The slope of the regression equation is 18.61, and it means that per capita income increases by $18.61 for each passing year. ŷ = 785 when the year is 1900, and ŷ = 2,646 when the year is 2000.
i. There do not appear to be any outliers.
Chapter 13. F Distribution and One-Way ANOVA
Section 2. The F Distribution and the F-Ratio

TRY IT 13.1
As part of an experiment to see how different types of soil cover would affect slicing tomato production, Marist College students grew tomato plants under different soil cover conditions. Groups of three plants each had one of the following treatments
    • bare soil
    • a commercial ground cover
    • black plastic
    • straw
    • compost
All plants grew under the same conditions and were the same variety. Students recorded the weight (in grams) of tomatoes produced by each of the n = 15 plants:

| Bare | Ground Cover | Plastic | Straw | Compost |
|---:|---:|---:|---:|---:|
| 2,625 | 5,348 | 6,583 | 7,285 | 6,277 |
| 2,997 | 5,682 | 8,560 | 6,897 | 7,818 |
| 4,915 | 5,482 | 3,830 | 9,230 | 8,677 |

: Table 13.4

Create the one-way ANOVA table.
Solution:
Enter the data into lists L1, L2, L3, L4 and L5. Press STAT and arrow over to TESTS. Arrow down to ANOVA. Press ENTER and enter L1, L2, L3, L4, L5). Press ENTER. The table was filled in with the results from the calculator.
One-Way ANOVA table:

| Source of Variation | Sum of Squares (SS) | Degrees of Freedom (df) | Mean Square (MS) | F |
|---|---:|---:|---:|---:|
| Factor (Between) | 36,648,561 | 5 – 1 = 4 | 9,162,140 | 4.4810 |
| Error (Within) | 20,446,726 | 15 – 5 = 10 | 2,044,672.6 | |
| Total | 57,095,287 | 15 – 1 = 14 | | |



Section 3. Facts About the F Distribution

TRY IT 13.2
There are multiple variants of the virus that causes COVID-19. The length of hospital stays for patients afflicted with various strains of COVID-19 is shown in Table 13.6. 
Test whether the mean length of hospital stay is the same or different for the various strains of COVID-19. Construct the ANOVA table, find the p-value, and state your conclusion. Use a 5% significance level.
.

| Delta Strain | Omicron Strain | Alpha Strain | Gamma Strain | Beta Strain |
|---:|---:|---:|---:|---:|
| 13.9 | 11.7 | 18.2 | 16.9 | 9.3 |
| 14.9 | 15.1 | 14.6 | 12.8 | 15.8 |
| 16.8 | 9.9 | 10.1 | 11.2 | 16.4 |

: Table 13.6

Solution:
We test for the equality of mean length of hospital stay:
H0 : μ1 = μ2 = μ3 = μ4 = μ5

The one-way ANOVA table results are as shown:.

| Source of Variation | Sum of Squares (SS) | Degrees of Freedom (df) | Mean Square (MS) | F | p-value |
|---|---:|---:|---:|---:|---:|
| Factor (Between) | 14.056 | 5 – 1 = 4 | 3.514 | 0.353095 | 0.8362 |
| Error (Within) | 99.52 | 15 – 5 = 10 | | | |
| Total | 113.576 | 15 – 1 = 14 | | | |




Distribution for the test: F4,10
Probability Statement: p-value = P(F > 0.3531) = 0.8362
Compare α and the p-value: α = 0.05, p-value = 0.8362, α > p-value
Make a decision: Since α > p-value, we do not reject H0.
Conclusion: At the 5% significance level, there is insufficient evidence from these data that different strains of COVID-19 virus will cause a significant difference in the length of a hospital stay.
TRY IT 13.3
Four sports teams took a random sample of players regarding their GPAs for the last year. The results are shown in Table 13.8.

| Basketball | Baseball | Hockey | Lacrosse |
|---:|---:|---:|---:|
| 3.6 | 2.1 | 4.0 | 2.0 |
| 2.9 | 2.6 | 2.0 | 3.6 |
| 2.5 | 3.9 | 2.6 | 3.9 |
| 3.3 | 3.1 | 3.2 | 2.7 |
| 3.8 | 3.4 | 3.2 | 2.5 |

: Table 13.8 GPAs for four sports teams

Use a significance level of 5%, and determine if there is a difference in GPA among the teams.
Solution:
With a p-value of 0.9271, we decline to reject the null hypothesis. There is not sufficient evidence to conclude that there is a difference among the GPAs for the sports teams.
TRY IT 13.4
Another fourth grader also grew bean plants, but this time in a jelly-like mass. The heights were (in inches) 24, 28, 25, 30, and 32. Do a one-way ANOVA test on the four groups. Are the heights of the bean plants different? Use the same method as shown in Example 13.4.
Solution:
    • F = 0.9496
    • p-value = 0.4402
From the sample data, the evidence is not sufficient to conclude that the mean heights of the bean plants are different.
Section 4. Test of Two Variances

TRY IT 13.5
The New York Choral Society divides its singers who are men into four categories from highest voices to lowest: Tenor1, Tenor2, Bass1, Bass2. In the table are heights of the men in the Tenor1 and Bass2 groups. One suspects that taller men will have lower voices, and that the variance of height may go up with the lower voices as well. Do we have good evidence that the variance of the heights of singers in each of these two groups (Tenor1 and Bass2) are different?

| Tenor1 | Bass2 |
|---:|---:|
| 69 | 72 |
| 67 | 72 |
| 68 | 67 |
| 72 | 75 |
| 70 | 74 |
| 67 | 70 |
| 71 | 67 |
| 65 | 70 |
| 64 | 70 |
| 66 | 75 |
| 72 | 66 |
| 69 | 71 |
| 76 | 71 |
| 74 | 72 |
| 70 | 64 |
| 68 | 68 |
| 72 | 74 |
| 74 | 66 |
| 72 | 74 |
| 68 | 73 |
| 75 | 70 |
|  | 75 |
|  | 68 |
|  | 72 |
|  | 66 |
|  | 72 |

: Table 13.11

Solution:
The histograms are not as normal as one might like. Plot them to verify. However, we proceed with the test in any case.

Subscripts: T1= tenor1 and B2 = bass 2

The standard deviations of the samples are sT1 = 3.3302 and sB2 = 2.7208.

The hypotheses are

H0: σT12= σB22 and H0: σT12 ≠ σB22 (two tailed test)

The F statistic is 1.4894 with 20 and 25 degrees of freedom.

The p-value is 0.3430. If we assume alpha is 0.05, then we cannot reject the null hypothesis.

We have no good evidence from the data that the heights of Tenor1 and Bass2 singers have different variances (despite there being a significant difference in mean heights of about 2.5 inches.)
