---
title: "Lesson 1: A Motivating Example"
subtitle: "Statistical Estimation for Data Science and AI"
---

::: {.column-margin}
{{< video 01_a-motivating-example.mp4 >}}

[Transcript](01_a-motivating-example.en.txt){target="_blank"}
[Handout](02_video-slides-for-a-motivating-example_module2_lesson1.pdf){width=700 height=980}
:::

## Slides {#sec-maximum-likelihood-estimation}

We start this module on maximum likelihood estimation with an intuitive example [maximum likelihood estimate (MLE)]{.aside}.

::: {#def-maximum-likelihood}
## Maximum likelihood estimation

The [maximum likelihood principle](https://en.wikipedia.org/wiki/Maximum_likelihood_estimation) chooses the value in the parameter space that makes the observed data most likely.
For observed data $\mathbf{x}$ and parameter space $\Theta$, the maximum likelihood estimate is

$$
\hat{\theta} = \underset{\theta\in\Theta}{\operatorname{arg\,max}}
\;L(\theta;\mathbf{x}),
$$

where $L(\theta;\mathbf{x})$ is the likelihood of $\theta$ given the observed data.
:::

## A Motivating Coin-Flipping Example {#sec-motivating-coin-example}

::: {#exm-twenty-coin-flips}
## Twenty coin flips

Suppose a biased coin has probability of heads

$$
p\in\{0.2,0.3,0.8\}.
$$

The coin is flipped 20 times, producing

$$
\mathrm{H,H,T,H,H,H,H,T,H,H,H,H,H,T,H,H,H,H,H,H}.
$$

There are 17 heads and 3 tails. Of the three candidate values, $p=0.8$ makes an outcome with this many heads most plausible.
:::

To see the maximum likelihood procedure explicitly, consider only two coin flips.

## The Two-Flip Model {#sec-two-flip-model}

For $i=1,2$, define

$$
X_i =
\begin{cases}
1, & \text{if the }i\text{th flip is heads}, \\
0, & \text{if the }i\text{th flip is tails}.
\end{cases}
$$

Let

$$
p = P(\text{heads on any one flip}).
$$

The model is

$$
X_1,X_2
\overset{\mathrm{iid}}{\sim}
\operatorname{Bernoulli}(p),
\qquad
p\in\{0.2,0.3,0.8\}.
$$

## Joint Probability Mass Function {#sec-joint-pmf-two-flips}

Because the two flips are independent,

$$
\begin{aligned}
f_p(x_1,x_2)
&= P_p(X_1=x_1,X_2=x_2) \\
&= P_p(X_1=x_1)\, P_p(X_2=x_2) \\
&= p^{x_1}(1-p)^{1-x_1} \mathbf{1}_{\{0,1\}}(x_1) \; p^{x_2}(1-p)^{1-x_2} \mathbf{1}_{\{0,1\}}(x_2) \\
&= p^{x_1+x_2} (1-p)^{2-x_1-x_2} \mathbf{1}_{\{0,1\}^2}(x_1,x_2)
\end{aligned}
$$

For a fixed observed pair $(x_1,x_2)$, the likelihood is the same expression viewed as a function of $p$:

$$
L(p;x_1,x_2) = f_p(x_1,x_2).
$$

The joint probabilities are

| $p$ | $(x_1,x_2)=(0,0)$ | $(x_1,x_2)=(0,1)$ | $(x_1,x_2)=(1,0)$ | $(x_1,x_2)=(1,1)$ |
|---:|---:|---:|---:|---:|
| $0.2$ | $0.64$ | $0.16$ | $0.16$ | $0.04$ |
| $0.3$ | $0.49$ | $0.21$ | $0.21$ | $0.09$ |
| $0.8$ | $0.04$ | $0.16$ | $0.16$ | $0.64$ |

::: {.callout-note}
The source slide reports $0.06$ in the final entry of the $p=0.3$ row. The corrected value is $0.3^2=0.09$.
:::

## Selecting the Most Likely Parameter {#sec-selecting-most-likely-p}

::: {#exm-two-tails}
## Two tails

When the observed data are

$$
(x_1,x_2)=(0,0),
$$

the likelihood values are

$$
L(0.2;0,0)=0.64,
\qquad
L(0.3;0,0)=0.49,
\qquad
L(0.8;0,0)=0.04.
$$

Therefore,

$$
\hat{p}=0.2.
$$
:::

::: {#exm-one-head-one-tail}
## One head and one tail

When the observed data are either

$$
(x_1,x_2)=(0,1)
\qquad\text{or}\qquad
(x_1,x_2)=(1,0),
$$

the likelihood values are

$$
L(0.2;x_1,x_2)=0.16,
\qquad
L(0.3;x_1,x_2)=0.21,
\qquad
L(0.8;x_1,x_2)=0.16.
$$

Therefore,

$$
\hat{p}=0.3.
$$
:::

::: {#exm-two-heads}
## Two heads

When the observed data are

$$
(x_1,x_2)=(1,1),
$$

the likelihood values are

$$
L(0.2;1,1)=0.04,
\qquad
L(0.3;1,1)=0.09,
\qquad
L(0.8;1,1)=0.64.
$$

Therefore,

$$
\hat{p}=0.8.
$$
:::

## The Maximum Likelihood Estimator {#sec-mle-discrete-coin}

::: {#def-mle-discrete-coin}
## Maximum likelihood estimator
The maximum likelihood estimator is the function of the random sample that selects the likelihood-maximizing candidate:

$$
\hat{p}
=
\underset{p\in\{0.2,0.3,0.8\}}{\operatorname{arg\,max}}
\;
L(p;X_1,X_2).
$$

Equivalently,

$$
\hat{p}
=
\begin{cases}
0.2,
& \text{if }(X_1,X_2)=(0,0), \\[4pt]
0.3,
& \text{if }(X_1,X_2)=(0,1)\text{ or }(1,0), \\[4pt]
0.8,
& \text{if }(X_1,X_2)=(1,1).
\end{cases}
$$

Since $X_1+X_2$ is the number of heads, the same estimator can be written as

$$
\hat{p}
=
\begin{cases}
0.2, & \text{if }X_1+X_2=0, \\
0.3, & \text{if }X_1+X_2=1, \\
0.8, & \text{if }X_1+X_2=2.
\end{cases}
$$
:::

## Reflection

**Idea**: Choose the value in the *parameter space*^[support] that makes the observed data "most likely".



1.  This  raises more questions than it answers:
    - Where is *parameter space* -- it will define it as the support of the parameter in the PDF rather than the support for the events.
    - By saying making the observed data "most likely" we are making some tacit assumptions about the data generating process.
      - an observation is generated by some distribution with unknown parameters. i.e. the PDF but how do we know it is the right PDF all we have is the data?
      - the data has a valid joint distribution over all the samples.
      - there is a unique combination of parameters for which the joint distribution gets a maximum value. This is actually a strong assumption that isn't guaranteed to hold in practice. However let's go along with it for now.
    - Also we have a bit of a contradiction here. The data has been observed and we are told several times that it is fixed. 
        - ~~The joint PDF for any "point in the Parameter space" is a set with zero measure so correrespondly has 0 probability.~~ wrong.
        - The joint PDF for any "point in the Parameter space" is a product of PDFs with a fixed set of values for the parameters. We get a function that maps the n-samples to a probability value. However....
        - Any set of n samples corresponds to a point with measure zero in the n-dimensional space of all possible samples. So the probability of getting exactly that set of samples is zero.
        - But the data has already been observed making the data certain as in the certain event. So isn't the probability 1?
        - Either way we have an issue here. If we are dealing with zero probability events what does it mean to say that one parameter setting makes the data "more likely" than another? If we are dealing with certain events 

It seems like the Professor is skirting though these issues by changing the notaion but this is not realy done in any way that makes sense to me.

2. Jen knows the reason why the MLE is called that and is trying to make the intuition fit the literal name. Once you understand MLE you can see why it is called that, However if you are a first time learner this is just going to confuse you and annoy you.
3. At some level she realized this but seems to be waving the confused student off - you will understand it all by the time you get your PHD.
4. She spends more time on the broken notation than on the actual idea of MLE.

### Whats the MLE story, morning glory?

Say we have a good idea about the distribution that generated our data but we don't know its parameters. We want to infer the parameters based on N IID samples from the distribution.

If we repeated the experiment for generating the data arbitrary many times for each value of the parameters so that the probabilities of each outcome stabilized (i.e. the variance diminished sufficiently through the law of large numbers to allow us to pick the parameter that generates our dataset more often than any other. (Assuming that there are no ties) we would call this parameter the MLE.)

### Using the language of probability?

If we wanted to use the language of probability we might say 

"MLE is the parameter setting that gives the highest long run probability of generating the observed data in repeated experiments."

Unfortunately as we get closer to the optimal value we would need more and more repetitions to tell which one is better using this method so it is a thought experiment and not a practical method as in reality there is always some chance in a finite number of repetitions that the we would get the wrong parameter due to chance. 

However we are getting very close to a circular definition once we use probability in the definition of MLE as probability is the normalized likelihood while frequency is its precursor.

---

### Time Out 

I came back to this after I did the quiz and saw the next few videos. While I stand by the criticism above, I think that the following points summarize the key ideas behind MLE in a more complete way:

- MLE is the main **inference** method in the frequentist paradigm. That means it is an approach to the following problem: 
- **The problem**: Lets suppose we know this much about the data generating process - we have seen enough (i.e. N IID) samples and perhaps some other information to recognize its PDF^[in other courses we might learn about QMLEs that deal with picking the wrong PDF]. Given that we know distribution and we have , but we don't know its parameters. How can we infer some settings for the parameters that are as plausible as any other setting for the parameters? 
- The **big idea of inference** is that we want to reinterpret the PDF as a function of the parameters with the sample data as being fixed. Then we want play a statistical Sherlock holmes and infer the most plausible parameter settings given the data we have observed. We do this by looking for the maximum of the PDF reinterpreted as a function of the parameters.
- **The MoM approach**: One approach we have seen is the Method of Moments (MoM) where based on the Weak Law of Large Numbers we equate the sample moments to the theoretical moments and solve for the parameters. This gives us estimators for the parameters and all we need are easy to compute moments of the Empirical Distribution. I.e. the sample mean, variance etc.
- **The MLE approach**: Today we consider the Joint Distribution for all N samples. This is just the product of their individual distributions (since they are IID). Such a function is called the Likelihood Function and it represents the probability of getting the given outcome in N trials. The Professor calls this the probability of the data^[but our data may more complicated than just N-univarate samples.]. Then we find the values of the parameters that give the maximum value to this function. These values are called the Maximum Likelihood Estimators (MLEs) of the parameters.
- **The Bayesian (MAP) approach** we invert the probability of the data given the parameters  using Bayes theorem using a flat prior to minimize any assumption on the data. and get a posterior distribution over the parameters given the data.
- The actual problem becomes one of solving a system of first order differential equations to find the maximum of the Likelihood function with respect to the parameters.
- Caveats: 
    - The MLEs might not be unique.
    - The MLEs might not exist (e.g. if the likelihood is unbounded).
    - We might need to deal with parameters that are part of the support of the distribution.
    - The MLEs might be biased estimators of the parameters.
    - The MLEs might be intractable in closed form and require numerical methods to compute.
    - In practice we might use optimization algorithms like Gradient Descent, Newton-Raphson, or Expectation-Maximization to find the MLEs numerically.

### Reflections  II: 

1. Does the MLE make more sense more Bayesian statistics where parameters are random variables? [the bayesian view]{.column-margin}
     - In Bayesian statistics we treat parameters as random variables with prior distributions.  In that context, the MLE can be seen as a special case of the Maximum A Posteriori (MAP) estimation when we assume a uniform prior over the parameters. 
    We are essentially using minimal prior information about the parameters and letting the data drive the estimation entirely.
     - In Bayesian statistics we don't like point estimates and learn to work with full posterior distributions over parameters which we can then interpret in terms of credible intervals and highest posterior density regions. This is more like a zone of high credibility surrounded by region of increasing uncertainty

2. Besides MOM and MLE what would be the next estimators we would learn about in a frequentist stats course? [the view from 2000 ft]{.column-margin}
     - In a standard frequentist statistics curriculum, after mastering MOM and MLE, you typically transition from "how to find an estimator" to "how to find the best estimator."
     - Ordinary Least Squares (OLS)
     - Uniformly Minimum Variance Unbiased Estimators ([UMVUE](https://en.wikipedia.org/wiki/Uniformly_minimum_variance_unbiased_estimator))
        - Tools Used: 
            - [x] the [Rao-Blackwell Theorem](https://en.wikipedia.org/wiki/Rao%E2%80%93Blackwell_theorem) and 
            - [ ] the [Lehmann-Scheffé Theorem](https://en.wikipedia.org/wiki/Lehmann%E2%80%93Scheff%C3%A9_theorem),
          which provide the "recipe" for turning a simple estimator into a UMVUE using Sufficient Statistics. 
     - **Estimating Equations & [M-Estimators](https://en.wikipedia.org/wiki/M-estimator)** - which generalize MLE. These estimators minimize a specific "loss function" (like absolute error instead of squared error) to make the estimate less sensitive to outliers (robustness). 
     - **[Quasi-Maximum Likelihood](https://en.wikipedia.org/wiki/Quasi-maximum_likelihood_estimate) (QMLE)** - You use this when you suspect your assumed distribution (like "Normal") is wrong, but you still want to use the MLE formula. QMLE remains consistent even if the model is misspecified, provided the mean structure is correct. This addresses the reality that we often don't know the true data-generating distribution.


